#!/bin/bash

# Install dependencies
sudo apt-get update
sudo apt-get install build-essential git python3 python3-dev python3-pip openjdk-8-jdk

# Clone and install the Python for Android project
git clone https://github.com/kivy/python-for-android.git
cd python-for-android
sudo python3 setup.py install

# Install Android SDK and NDK
wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
unzip sdk-tools-linux-4333796.zip -d android-sdk
export ANDROID_SDK_ROOT=$(pwd)/android-sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools
yes | sdkmanager --licenses
sdkmanager "platforms;android-28" "build-tools;28.0.3" "ndk-bundle"

# Configure environment variables
echo 'export ANDROID_SDK_ROOT=$(pwd)/android-sdk' >> ~/.bashrc
echo 'export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools' >> ~/.bashrc

# Install Kivy
sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev python-setuptools libgstreamer1.0-dev git-core gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-{omx,alsa} python3-dev libmtdev-dev xclip
sudo pip3 install Cython==0.28.6
sudo pip3 install https://github.com/kivy/kivy/archive/master.zip
